### ISSUE TITLE
Calendar doesn't display

### ISSUE THREAD

**Issue by jeffbryner** [Tiska/aframe-3d-calendar-component#1]
Tried out the examples and I can't seem to get it to display. 

First problem was that: 
  <script src="https://unpkg.com/aframe-3d-calendar-component/dist/aframe-3d-calendar-component.min.js"></script> doesn't seem to exist? 

Changing it to: 
    <script src="https://cdn.rawgit.com/Tiska/aframe-3d-calendar-component/master/dist/aframe-3d-calendar-component.js"></script> 
works, but none of the example html shows a calendar in the 3D view? How do I make it go? ;-]

**Comment by Tiska** [comment]
Hi @jeffbryner, I fixed file naming. Thank you for your feedback :) I quickly launched the project and yes the calendar is not displayed, I'm trying to find why, last time I used it it was functional.

**Comment by jeffbryner** [comment]
Great, thanks! Looking forward to using it on a project.

**Comment by jeffbryner** [comment]
Great, thanks! Looking forward to using it on a project.

**Comment by Tiska** [comment]
Hi @jeffbryner, Happy New Year ! The bug was just a naming component (aframe-... => a-frame-...). You can try the component with v1.0.2 :)

**Comment by jeffbryner** [comment]
Excellent, thanks!
