### ISSUE TITLE
Mode 3next doesn't display

### ISSUE THREAD

**Issue by jeffbryner** [Tiska/aframe-3d-calendar-component#2]
In taking it for a spin, the docs say the modes are 'full' or '3next'. I got full to work no problem, but I can't get 3next to work: 
https://glitch.com/edit/#!/lace-tractor?path=index.html:27:58

I suspect it's something in here?
https://github.com/Tiska/aframe-3d-calendar-component/blob/101b2588c2af74bbb3229575e53263c62778833f/index.js#L204

**Comment by Tiska** [comment]
Hi @jeffbryner, I tried your example, just remove the position : my 3next months mode is a little different, months squares display on the ground so don't use a position to low :)

**Comment by jeffbryner** [comment]
Ahh, I see, thanks! Sorry for the issue. What would be a good starting position/rotation?

**Comment by Tiska** [comment]
just 000 for rotation and position :)
